- name: add mongo ppa key
  apt_key: >
    keyserver=hkp://keyserver.ubuntu.com:80
    id=7F0CEB10
    state=present

- name: add mongo sources list
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen'

- name: install mongo
  apt: name=mongodb-10gen state=latest update_cache=yes

- name: create service directory
  file: path=/etc/sv/mongodb state=directory

- name: create run script
  template: src=run dest=/etc/sv/mongodb/run mode=0755
