- name: download deb package
  get_url: >
    url=http://sphinxsearch.com/files/sphinxsearch_2.2.4-release-0ubuntu12~trusty_amd64.deb
    dest=/tmp/sphinxsearch_2.2.4-release-0ubuntu12~trusty_amd64.deb
  register: sphinxsearch_download_result

- name: install package
  shell: >
    dpkg -i /tmp/sphinxsearch_2.2.4-release-0ubuntu12~trusty_amd64.deb
  when: sphinxsearch_download_result | changed
