- name: provides a ssh github private key
  copy: src=.id_github.txt dest={{ github_ssh_path }} owner=vexor group=vexor mode=700

#- name: git clone big repositories on the images
#  git: repo=https://github.com/{{item}}.git dest={{git_repositories_root}}/{{item}} accept_hostkey=yes
#  with_items:
#     - bebanjo/almodovar

#- name: git clone big repositories on the images
#  git: repo=git@github.com:{{item}}.git dest={{git_repositories_root}}/{{item}} key_file={{ github_ssh_path }} accept_hostkey=yes
#  with_items:
#    - bebanjo/capistrano-bebanjo
#    - bebanjo/sequence
#    - bebanjo/movida
#    - bebanjo/panorama
#    - bebanjo/sheriff