- name: mysql newest ppa
  apt_repository: repo='ppa:ondrej/mysql-{{mysql_version}}' state=present

- name: install server packages
  apt: pkg={{item}} state=latest
  environment:
    RUNLEVEL: '1'
  with_items:
    - libmysqlclient-dev
    - mysql-server-{{mysql_version}}

- name: tune my.cnf
  shell: >
    echo "
      set /files/etc/mysql/my.cnf/target[. = 'mysqld']/collation_server utf8_unicode_ci
      set /files/etc/mysql/my.cnf/target[. = 'mysqld']/character_set_server utf8
      set /files/etc/mysql/my.cnf/target[. = 'mysqld']/sync_frm 0
      set /files/etc/mysql/my.cnf/target[. = 'mysqld']/innodb-flush-log-at-trx-commit 0
      set /files/etc/mysql/my.cnf/target[. = 'mysqld']/innodb-doublewrite 0
      set /files/etc/mysql/my.cnf/target[. = 'mysqld']/innodb-checksums 0
      set /files/etc/mysql/my.cnf/target[. = 'mysqld']/innodb_support_xa 0
      save
    " | augtool

- name: stop mysql server
  service: name=mysql state=stopped
